select
ettsrc,
ettrxc,
ettype,
etmacc,
etnhdl,
etcont,
etrprc,
etlmtg,
CAST(CAST( ettdes  AS CHAR(200) CCSID 65535) AS CHAR(40) CCSID 935) as ettdes,
CAST(CAST( ettabv  AS CHAR(200) CCSID 65535) AS CHAR(40) CCSID 935) as ettabv,
ettrid,
ettltx,
ettltx1,
etarvs,
etrutn,
etmisc,
etlmti,
etminc,
etmaxc,
etchrg,
etrutn1,
ettmod
from	 EBPDPRM.EBPTRC  where  $CONDITIONS
